### ISSUE TITLE
Move Header from Index.html into "src/containers" directory

### ISSUE THREAD

**Issue by dorono** [ResistanceCalendar/resistance-calendar-client#4]
I started working on this (in the src/components folder, which can be deleted), but never finished. Right now the header is hard-coded in the index.html file. 

At the moment, the header is just a div with an image in it, but it will eventually contain a lot more. 

Since this header may eventually very well contain other elements that need to communicate with the global state (maybe a search bar or something that triggers an action on the global state), my suggestion is to make this a "smart component" or container. 

This is just my suggestion, but I thought I'd make not of it here so it didn't fall between the cracks.

**Comment by dentemple** [comment]
Closed by recent merge.  The header is now a jsx component.

**Comment by dorono** [comment]
@dentemple Great work, you're totally kicking ass! I think you probably know, but just to clarify my initial comment where I write: "(in the src/components folder, which can be deleted)" - I meant to say: "(in the src/components/Header folder, which can be deleted)".

I definitely recommend we keep a "components" directory around in addition to the containers. 

Again, probably obvious, but just wanted to avoid any confusion. :)
